cp exec.c /home/ubuntu/rolex10/fs
cp stat.c /home/ubuntu/rolex10/fs
cp open.c /home/ubuntu/rolex10/fs
cp read_write.c /home/ubuntu/rolex10/fs
cp namespace.c /home/ubuntu/rolex10/fs
cp inode.c /home/ubuntu/rolex10/fs/devpts
cp hooks.c /home/ubuntu/rolex10/security/selinux
cp input.c /home/ubuntu/rolex10/drivers/input
cp rolex_defconfig /home/ubuntu/rolex10/arch/arm64/configs
